const STORAGE='ledger-holdings-v1',KEY='ledger-stooq-key-v1',SNAPSHOT='ledger-eod-snapshot-2026-09-04-v2';
const seed=[
 {id:'mazda',name:'マツダ',ticker:'7261',category:'日本株',quantity:500,cost:1123,price:1175.5},
 {id:'nnfh',name:'西日本フィナンシャルホールディングス',ticker:'7189',category:'日本株',quantity:100,cost:4027,price:4929},
 {id:'nci',name:'日本化学工業',ticker:'4092',category:'日本株',quantity:100,cost:3300,price:5260},
 {id:'shiseido',name:'資生堂',ticker:'4911',category:'日本株',quantity:100,cost:3075,price:3445},
 {id:'jmacs',name:'JMACS',ticker:'5817',category:'日本株',quantity:100,cost:1700,price:1062},
 {id:'yaskawa',name:'安川電機',ticker:'6506',category:'日本株',quantity:100,cost:4505,price:4570},
 {id:'emaxis-sp500',name:'ｅＭＡＸＩＳ Ｓｌｉｍ 米国株式（Ｓ＆Ｐ５００）',ticker:'03311187',category:'投資信託',quantity:177286,cost:28204,price:44392,unitSize:10000}
];
function load(){try{const stored=JSON.parse(localStorage.getItem(STORAGE));if(!Array.isArray(stored))return structuredClone(seed);if(!localStorage.getItem(SNAPSHOT)){seed.forEach(s=>{const found=stored.find(h=>h.ticker===s.ticker);if(found)Object.assign(found,structuredClone(s));else stored.push(structuredClone(s))});localStorage.setItem(SNAPSHOT,'1');localStorage.setItem(STORAGE,JSON.stringify(stored))}return stored}catch{return structuredClone(seed)}}
let holdings=load();const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:1}).format(n),num=n=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:4}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const calc=h=>{const u=h.quantity/(h.unitSize||1),cost=u*h.cost,value=u*h.price,profit=value-cost;return{cost,value,profit,pct:cost?profit/cost*100:0}};const save=()=>localStorage.setItem(STORAGE,JSON.stringify(holdings));
function render(){const totals=holdings.reduce((a,h)=>{const v=calc(h);a.cost+=v.cost;a.value+=v.value;a.profit+=v.profit;return a},{cost:0,value:0,profit:0});const sign=totals.profit>=0?'+':'';document.querySelector('#total').textContent=yen(totals.value);const top=document.querySelector('#total-profit');top.textContent=`${sign}${yen(totals.profit)} (${(totals.profit/totals.cost*100).toFixed(2)}%)`;top.className=totals.profit>=0?'positive':'negative';document.querySelector('#profit').textContent=`${sign}${yen(totals.profit)}`;document.querySelector('#profit').className=totals.profit>=0?'positive':'negative';document.querySelector('#cost').textContent=yen(totals.cost);document.querySelector('#count').textContent=`${holdings.length}銘柄`;renderMap(totals.value);renderList()}
function renderMap(total){document.querySelector('#heatmap').innerHTML=holdings.map(h=>{const v=calc(h),opacity=Math.min(.94,.28+Math.min(Math.abs(v.pct)/16,.66)),color=v.profit>=0?`rgba(26,203,135,${opacity})`:`rgba(239,98,100,${opacity})`;return `<button class="tile" data-edit="${h.id}" style="background:${color}"><span>${esc(h.ticker)}</span><b>${yen(v.value)}</b><small>${v.pct>=0?'+':''}${v.pct.toFixed(1)}%</small></button>`}).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit))}
function renderList(){document.querySelector('#list').innerHTML=holdings.map(h=>{const v=calc(h),klass=v.profit>=0?'positive':'negative',unit=h.unitSize?'／1万口':'';return `<article class="holding"><div class="holding-top"><div><h2>${esc(h.name)}</h2><span class="code">${esc(h.ticker)} · ${esc(h.category)}</span></div><div class="value">${yen(v.value)}</div></div><div class="holding-bottom"><div><small>取得 ${yen(h.cost)}${unit}</small><b>${num(h.quantity)}${h.unitSize?'口':''}</b></div><div><small>損益</small><b class="${klass}">${v.profit>=0?'+':''}${yen(v.profit)}　${v.pct>=0?'+':''}${v.pct.toFixed(2)}%</b></div></div><div class="actions"><button data-edit="${h.id}">編集</button><button data-delete="${h.id}">削除</button></div></article>`}).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const h=holdings.find(x=>x.id===b.dataset.delete);if(h&&confirm(`「${h.name}」を削除しますか？`)){holdings=holdings.filter(x=>x.id!==h.id);save();render()}})}
const dialog=document.querySelector('#editor'),form=document.querySelector('#form');function openEditor(id){const h=holdings.find(x=>x.id===id);form.reset();['id','name','ticker','category','quantity','cost-input','price'].forEach(k=>{const prop=k==='cost-input'?'cost':k;document.querySelector('#'+k).value=h?.[prop]??''});document.querySelector('#form-title').textContent=h?'銘柄を編集':'銘柄を追加';dialog.showModal()}
document.querySelector('#add').onclick=()=>openEditor();document.querySelector('#save').onclick=()=>{if(!form.reportValidity())return;const id=document.querySelector('#id').value,prior=holdings.find(h=>h.id===id),entry={id:id||crypto.randomUUID(),name:document.querySelector('#name').value.trim(),ticker:document.querySelector('#ticker').value.trim().toUpperCase(),category:document.querySelector('#category').value.trim(),quantity:Number(document.querySelector('#quantity').value),cost:Number(document.querySelector('#cost-input').value),price:Number(document.querySelector('#price').value),unitSize:prior?.unitSize};if(id)holdings=holdings.map(h=>h.id===id?entry:h);else holdings.push(entry);save();dialog.close();render()};
function status(s,err=false){const e=document.querySelector('#status');e.textContent=s;e.className=err?'negative':''}function parse(csv){const l=csv.trim().split(/\r?\n/);const close=Number(l[1]?.split(',')[6]);if(!Number.isFinite(close))throw Error('価格データを取得できません');return close}async function refresh(){const key=localStorage.getItem(KEY)||'';if(!key){status('APIキーを設定してください。',true);return}const targets=holdings.filter(h=>/^\d{4,5}$/.test(h.ticker));const b=document.querySelector('#refresh');b.disabled=true;b.textContent='更新中';try{for(const h of targets){const res=await fetch(`https://stooq.com/q/l/?s=${h.ticker.toLowerCase()}.jp&i=d&apikey=${encodeURIComponent(key)}`);h.price=parse(await res.text())}save();render();status(`${targets.length}銘柄を終値で更新しました。`)}catch(e){status(`更新できませんでした：${e.message}`,true)}finally{b.disabled=false;b.textContent='↻ 更新'}}
document.querySelector('#api-key').value=localStorage.getItem(KEY)||'';document.querySelector('#save-key').onclick=()=>{const k=document.querySelector('#api-key').value.trim();if(!k){status('APIキーを入力してください。',true);return}localStorage.setItem(KEY,k);status('設定を保存しました。')};document.querySelector('#refresh').onclick=refresh;render();

